# Generated by Django 4.1.5 on 2023-01-28 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('password', models.CharField(
                    max_length=128,
                    verbose_name='password'
                )),
                ('last_login', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='last login'
                )),
                ('is_superuser', models.BooleanField(
                    default=False,
                    help_text='Designates that this user has all permissions'
                              ' without explicitly assigning them.',
                    verbose_name='superuser status'
                )),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(
                    blank=True,
                    help_text='The groups this user belongs to.'
                              ' A user will get all permissions'
                              ' granted to each of their groups.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.group', verbose_name='groups'
                )),
                ('user_permissions', models.ManyToManyField(
                    blank=True,
                    help_text='Specific permissions for this user.',
                    related_name='user_set',
                    related_query_name='user',
                    to='auth.permission',
                    verbose_name='user permissions'
                )),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=255, unique=True)),
                ('disciplines', models.ManyToManyField(
                    blank=True,
                    related_name='specialties',
                    to='api.discipline'
                )),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('user_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to=settings.AUTH_USER_MODEL
                 )),
                ('work_experience', models.IntegerField()),
                ('post', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('group_code', models.CharField(max_length=6, unique=True)),
                ('sex', models.CharField(
                    choices=[('male', 'Male'), ('female', 'Female')],
                    max_length=6
                )),
                ('max_students', models.IntegerField(default=20)),
                ('specialty',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     related_name='study_groups',
                     to='api.specialty'
                 )),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to=settings.AUTH_USER_MODEL
                 )),
                ('avg_grade', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    max_digits=3
                )),
                ('study_group', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='students',
                    to='api.studygroup'
                )),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
        ),
        migrations.AddField(
            model_name='specialty',
            name='curator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='specialty',
                to='api.curator'
            ),
        ),
    ]
