# Generated by Django 4.1.5 on 2023-02-01 18:11

from django.db import connection
from django.db import migrations


def insert_data(apps, schema_editor):
    sql = """
insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5000,'Lorri', 'Cullivan', 'lvanezise@blogger.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_curator (user_ptr_id, work_experience, post) values (5000, 15, 'Vanezis');
insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5001, 'Seumas', 'Lundbeck', 'smacgatrickf@tumblr.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_curator (user_ptr_id, work_experience, post) values (5001, 16, 'MacGilpick');
insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5002, 'Braden', 'Mateuszczyk', 'bsaffellg@github.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_curator (user_ptr_id, work_experience, post) values (5002, 17, 'Saffell');


insert into api_specialty (id,name) values (6000, 'Hell');
insert into api_specialty (id,name) values (6001, 'Useless');
insert into api_specialty (id,name) values (6002, 'No Way Out');
insert into api_specialty (id,name) values (6003, 'Mordor');

insert into api_discipline (id, name, description) values (9000, 'Math', 'sdfsdf');
insert into api_discipline (id, name, description) values (9001, 'Temp', 'sdfsdf');
insert into api_discipline (id, name, description) values (9002, 'Mineral Oil', 'sdfsdf');
insert into api_discipline (id, name, description) values (9003, 'Valacyclovir', 'sdfsdf');
insert into api_discipline (id, name, description) values (9004, 'PE', 'sdfsdf');
insert into api_discipline (id, name, description) values (9005, 'Physics', 'sdfsdf');
insert into api_discipline (id, name, description) values (9006, 'English', 'sdfsdf');
insert into api_discipline (id, name, description) values (9007, 'Philosophy', 'sdfsdf');
insert into api_discipline (id, name, description) values (9008, 'Law', 'sdfsdf');
insert into api_discipline (id, name, description) values (9009, 'Smth', 'sdfsdf');

insert into api_studygroup (id, group_code, specialty_id, max_students) values (7000, 'asd', 6001, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7001, 'asd1', 6001, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7002, 'asd2', 6001, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7003, 'asd3', 6002, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7004, 'asd4', 6002, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7005, 'asd5', 6002, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7006, 'asd6', 6003, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7007, 'asd7', 6003, 20);
insert into api_studygroup (id, group_code, specialty_id, max_students) values (7008, 'asd8', 6003, 20);


insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5003, 'Jessy', 'Ken', 'sdfwe12341.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5003, 7000, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5004, 'Braden', 'Mateuszczyk', 'sdfweasd12341.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5004,  7000, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5005, 'Paul', 'Walker', 'sdfwe15672341.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5005, 7000, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5006, 'JAmes', 'Smith', 'lkjh.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5006, 7001, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5007, 'Rocky', 'Balboa', 'lkj11h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5007, 7001, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5008, 'Artemiy', 'Panarin', 'lkj22h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5008, 7001, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5009, 'Dmitry', 'Orlov', 'lkj5h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5009, 7001, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5010, 'Euhenio', 'Kuznetsov', 'lkj33h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5010, 7000, 0, 'female');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5011, 'Leam', 'Nisson', 'lkj44h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5011, 7000, 0, 'female');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5012, 'Toyta', 'Camry', 'l7kjh.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5012, 7000, 0, 'female');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5013, 'Volkswagen', 'Golf', 'lkj8h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5013, 7004, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5014, 'I am', 'Tired', 'lkjds54h.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5014, 7004, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5015,'Inserting', 'These names', 'irf.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5015, 7004, 0, 'male');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5016,'help', 'me', 'w2er.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5016, 7004, 0, 'female');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5017,'i', 'beg', 'wss2er.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5017, 7004, 0, 'female');

insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (5018,'you', 'allah', 'w2s8der.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, false, false);
insert into api_student (user_ptr_id, study_group_id, avg_grade, sex) values (5018, 7004, 0, 'female');


insert into api_user (id, first_name, last_name, email, password, deleted, is_admin, is_superuser) values (10000, 'admin', 'admin', 'admin@mail.com', 'pbkdf2_sha256$390000$VHECVsJapUwR6T68vC612O$Q5Q5VTgGiVLLDNdzCFjGHar4Wj8/yfFzRTpx+pn0nBg=', false, true, false);


update api_specialty set curator_id = 5000 where id = 6000;
update api_specialty set curator_id = 5001 where id = 6001;
update api_specialty set curator_id = 5002 where id = 6002;
update api_specialty set curator_id = 5002 where id = 6003;


insert into api_specialty_disciplines (specialty_id, discipline_id) values (6000, 9001);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6000, 9002);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6000, 9005);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6000, 9004);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6000, 9008);

insert into api_specialty_disciplines (specialty_id, discipline_id) values (6001, 9000);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6001, 9004);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6001, 9008);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6001, 9003);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6001, 9009);

insert into api_specialty_disciplines (specialty_id, discipline_id) values (6002, 9004);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6002, 9008);

insert into api_specialty_disciplines (specialty_id, discipline_id) values (6003, 9003);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6003, 9004);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6003, 9005);
insert into api_specialty_disciplines (specialty_id, discipline_id) values (6003, 9008);"""

    with connection.cursor() as cursor:
        cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
