# Generated by Django 4.1.5 on 2023-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_avg_grade_alter_student_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={'permissions': [('can_manipulate_students', 'Can manipulate students'), ('can_manipulate_student_groups', 'Can manipulate student groups')]},
        ),
        migrations.AlterField(
            model_name='specialty',
            name='disciplines',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialties', to='api.discipline'),
        ),
    ]
