# Generated by Django 4.1.5 on 2023-01-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_curator_options_alter_specialty_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.curator'),
        ),
    ]
