# Generated by Django 4.1.5 on 2023-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_specialty_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='api.discipline'),
        ),
    ]
