# Generated by Django 4.1.5 on 2023-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_discipline_name_alter_specialty_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
