# Generated by Django 4.1.5 on 2023-01-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_discipline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group',
            new_name='study_group',
        ),
        migrations.AlterField(
            model_name='specialty',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specialty', to='api.curator'),
        ),
    ]
