# Generated by Django 4.1.5 on 2023-01-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_group_student_study_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.studygroup'),
        ),
    ]
