# Generated by Django 4.1.5 on 2023-01-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studygroup_sex_alter_student_study_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curator',
            options={},
        ),
        migrations.AddField(
            model_name='curator',
            name='post',
            field=models.CharField(default='teacher', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curator',
            name='work_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
