# Generated by Django 4.1.5 on 2023-02-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_file_alter_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
